export const data = [
  {
    id: 1,
    title: "Buttermilk Pancakes",
    category: "breakfast",
    price: "$ 15.99",
    img: "https://images.pexels.com/photos/6072377/pexels-photo-6072377.jpeg?cs=srgb&dl=pexels-alesia-kozik-6072377.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 2,
    title: "Dinner Double",
    category: "lunch",
    price: "$ 13.99",
    img: "https://images.pexels.com/photos/5908287/pexels-photo-5908287.jpeg?cs=srgb&dl=pexels-katerina-holmes-5908287.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 3,
    title: "Godzilla Milkshake",
    category: "shakes",
    price: "$ 6.99",
    img: "https://images.pexels.com/photos/6174871/pexels-photo-6174871.jpeg?cs=srgb&dl=pexels-teguh-sugi-6174871.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 4,
    title: "Country Delight",
    category: "breakfast",
    price: "$ 20.99",
    img: "https://images.pexels.com/photos/5908226/pexels-photo-5908226.jpeg?cs=srgb&dl=pexels-katerina-holmes-5908226.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 5,
    title: "Egg Attack",
    category: "lunch",
    price: "$ 22.99",
    img: "https://images.pexels.com/photos/4393010/pexels-photo-4393010.jpeg?cs=srgb&dl=pexels-spencer-davis-4393010.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 6,
    title: "Oreo Dream",
    category: "shakes",
    price: "$ 18.99",
    img: "https://images.pexels.com/photos/725991/pexels-photo-725991.jpeg?cs=srgb&dl=pexels-dana-tentis-725991.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 7,
    title: "Bacon Overflow",
    category: "breakfast",
    price: "$ 8.99",
    img: "https://images.pexels.com/photos/7937464/pexels-photo-7937464.jpeg?cs=srgb&dl=pexels-nicola-barts-7937464.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 8,
    title: "American Classic",
    category: "lunch",
    price: "$ 12.99",
    img: "https://images.pexels.com/photos/2871757/pexels-photo-2871757.jpeg?cs=srgb&dl=pexels-%E5%A5%A5%E5%B0%BC%E5%B0%94-%E5%AD%99-2871757.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 9,
    title: "African Special",
    category: "shakes",
    price: "$ 10.99",
    img: "https://images.pexels.com/photos/410648/pexels-photo-410648.jpeg?cs=srgb&dl=pexels-pascal-claivaz-410648.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
  {
    id: 10,
    title: "Steak dinner",
    category: "dinner",
    price: "$ 39.99",
    img: "https://images.pexels.com/photos/361184/asparagus-steak-veal-steak-veal-361184.jpeg?cs=srgb&dl=pexels-pixabay-361184.jpg&fm=jpg&h=200&w=200&fit=crop",
    desc: " Lorem ipsum, dolor sit amet consectetur adipisicing elit. Blanditiis reprehenderit voluptate quisquam libero quasi sapiente eaque iste vero, laborum dolores.",
  },
];
